// seed.js — Run this ONCE in the browser console (or a local Node script with
// firebase-admin) to seed the matches collection in Firestore using the exact
// slug IDs generated by assets/data.js so they match the runtime app data.
//
// Usage in browser (after loading firebase.js as a module):
//   import { seedMatches } from './seed.js';
//   seedMatches();

import { db } from "./assets/firebase.js";
import { WC_MATCHES } from "./assets/data.js";
import {
  doc,
  setDoc,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

export async function seedMatches() {
  const matches = WC_MATCHES.map(match => ({
    ...match,
    home: match.home?.name || match.home,
    away: match.away?.name || match.away,
  }));

  let count = 0;
  for (const match of matches) {
    const { id, ...data } = match;
    await setDoc(doc(db, "matches", String(id)), {
      ...data,
      sourceUpdatedAt: serverTimestamp()
    });
    count++;
    console.log(`Seeded match ${count}/${matches.length}: ${id}`);
  }

  console.log(`✅ Seeded ${count} matches into Firestore with slug IDs from assets/data.js.`);
}
